### ISSUE TITLE
Add support for YourTTS voice conversion

### ISSUE THREAD

**Issue by gukush** [gukush/audio-watermark-242#10]
https://github.com/Edresson/YourTTS

The aim of this task is to analyze solution and integrate it into our voice cloning inventory

**Comment by MDG369** [comment]
YourTTS model is included in coqui-ai-tts models, so the implementation works the same as in issue #7.  
Example TTS command: ```tts --model_name tts_models/multilingual/multi-dataset/your_tts  --speaker_wav /audio/voice-jewish-1.wav --reference_wav  /audio/voice-polish-8.wav --language_idx "en"```
The converted audio file is of low quality and the speakers are not recognizable.

**Comment by MDG369** [comment]
Test in the form of a python script was added in commit cb49316eef41f08fc4999154a762a66bda3b4d0c

**Comment by gukush** [comment]
For some reason coqui-ai-tts doesn't utilize this in their API:
 python yourtts_test.py 
Traceback (most recent call last):
  File "/project/tests/yourtts_test.py", line 7, in <module>
    tts.voice_conversion_to_file(source_wav="/audio/voice-hispanic-1.wav", target_wav="/audio/voice-polish-8.wav", file_path="output.wav")
  File "/project/coqui-ai-TTS/TTS/api.py", line 377, in voice_conversion_to_file
    wav = self.voice_conversion(source_wav=source_wav, target_wav=target_wav)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/coqui-ai-TTS/TTS/api.py", line 358, in voice_conversion
    wav = self.voice_converter.voice_conversion(source_wav=source_wav, target_wav=target_wav)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Changed the test so that it calls the CLI app from subprocess in commit 48b84606713bae17d06dd526c72a977e8cc85de7
