### ISSUE TITLE
Add support for VITS voice cloning 

### ISSUE THREAD

**Issue by gukush** [gukush/audio-watermark-242#11]
https://github.com/jaywalnut310/vits

The aim of this task is to analyze solution and integrate this voice cloning technique into the repo

**Comment by AleksanderKr** [comment]
Currently: during requirements installation for VITS there's "ModuleNotFoundError: No module named 'distutils.msvccompiler" despite having _setuptools_ installed. The error is rather popular, I think I should find a solution soon (ETA 10.11.2024)

**Comment by AleksanderKr** [comment]
TTS models are low quality, rather unusable.

Voice converter currently throws an errror:

Traceback (most recent call last):
  File "/home/krucz/pbadawczy_v2/audio-watermark-242/vits/vits_tts_test.py", line 84, in <module>
    dataset = TextAudioSpeakerLoader(hps_ms.data.validation_files, hps_ms.data)
  File "/home/krucz/pbadawczy_v2/audio-watermark-242/vits/data_utils.py", line 176, in __init__
    self._filter()
  File "/home/krucz/pbadawczy_v2/audio-watermark-242/vits/data_utils.py", line 191, in _filter
    lengths.append(os.path.getsize(audiopath) // (2 * self.hop_length))
  File "/home/krucz/.pyenv/versions/3.10.15/lib/python3.10/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'DUMMY2/p234/p234_071.wav'

Suggested data preprocessing was done (using provided scripts). Still working on that
