### ISSUE TITLE
Create cloned samples and test watermark detection

### ISSUE THREAD

**Issue by gukush** [gukush/audio-watermark-242#18]
1 Pick consistent samples which will be used to derive voice for cloning purposes.
2 For each cloning technique:
- take watermarked dataset
- create new samples which use voices cloned from point 1
- run watermark detection for new outputs

**Comment by gukush** [comment]
While cloning with Silentcipher encountered following issue with some files (not all):

Traceback (most recent call last):
  File "/project/main.py", line 154, in <module>
    main(args)
  File "/project/main.py", line 87, in main
    voice_clone_samples(samples,clones,voices,args.override)
  File "/project/main.py", line 71, in voice_clone_samples
    cloned_audio, sr = clone.clone_voice_to_sample(sample,voice)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/voice_cloning/openvoice_cloner.py", line 34, in clone_voice_to_sample
    sample_se, sample_name = se_extractor.get_se(sample,self.tone_color_converter,vad=False)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/project/OpenVoice/openvoice/se_extractor.py", line 152, in get_se
    raise NotImplementedError('No audio segments found!')
NotImplementedError: No audio segments found!

**Comment by gukush** [comment]
Distortions (task 2):
@JakubGlisz - pitch shifting, reverb
@MDG369  - lower bit depth, lower sampling rate
@AleksanderKr  - adding noise
@bmaz-dev - lossy compression
@Cimin123 - high-pass and low-pass filter
